// <auto-generated />
namespace IMC_webApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class meher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(meher));
        
        string IMigrationMetadata.Id
        {
            get { return "201510040016101_meher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
